-- Table: user_password
CREATE TABLE IF NOT EXISTS user_password (
    USER_NAME VARCHAR(150) DEFAULT NULL,
    USER_PASSWORD VARCHAR(20) DEFAULT NULL
    );

-- Table: Student. Refer com.college.student.pojo.Student
CREATE TABLE IF NOT EXISTS student (
    ROLL_NO INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) DEFAULT NULL,
    AGE TINYINT DEFAULT NULL,
    PHONE_NUMBER INT DEFAULT NULL,
    GENDER VARCHAR(10) DEFAULT NULL
    );

-- Table: Address. Refer com.college.student.pojo.Address
CREATE TABLE IF NOT EXISTS address (
    COUNTRY VARCHAR(255) DEFAULT NULL,
    STATE VARCHAR(255) DEFAULT NULL,
    CITY VARCHAR(255) DEFAULT NULL,
    ROLL_NO INT DEFAULT NULL,
    ADDRESS_TYPE ENUM('PERMANENT','TEMPORARY') DEFAULT NULL,
    KEY rollNo (ROLL_NO),
    CONSTRAINT fk_address_student FOREIGN KEY (ROLL_NO) REFERENCES student(ROLL_NO)
    );

-- Table: Admission. Refer com.college.student.pojo.Admission
CREATE TABLE IF NOT EXISTS admission (
    COURSE VARCHAR(255) DEFAULT NULL,
    SECTION INT DEFAULT NULL,
    ADMISSION_YEAR YEAR DEFAULT NULL,
    ROLL_NO INT DEFAULT NULL,
    UNIQUE KEY ROLL_NO (ROLL_NO),
    CONSTRAINT fk_admission_student FOREIGN KEY (ROLL_NO) REFERENCES student(ROLL_NO)
    );
